### ISSUE TITLE
请在这里简单描述一下问题

### ISSUE THREAD

**Issue by railgun0325** [BewlyBewly/BewlyBewly#1110]
### 环境

浏览器 ( Chrome):
浏览器版本 (版本 130.0.6723.92（正式版本） （64 位）):
BewlyBewly 版本 (如 0.34.2):

### 问题描述

![image](https://github.com/user-attachments/assets/7e94383c-26a5-4711-8cc6-8d6dedb4c45e)
右上角顶栏位置，将鼠标悬置与其上方的时候出现的画面非常糊，明显不清晰。是不是和显示器有关，我使用的2k显示器，左边正常网页画面很清晰，就这里的内容很模糊。

**Comment by apades** [comment]
这是毛玻璃效果导致的，关闭就好了

@hakadao 这里transform + backdrop-filter会导致文字模糊的，定位只用top + left就不会出现了

**Comment by BruceWae** [comment]
Safari中的个人界面显示不出来，点进去就是登陆了，但相关的收藏和浏览器记录并不存在，我尝试了最新的几个版本都是一样的问题
<img width="150" alt="image" src="https://github.com/user-attachments/assets/35949fa0-a68d-41cf-96b1-2969d90de447">
<img width="553" alt="image" src="https://github.com/user-attachments/assets/32dc4a55-8d75-401f-80ee-5ff7af7039b3">
<img width="1283" alt="image" src="https://github.com/user-attachments/assets/6511a3c9-2b18-4559-aad4-2ec1143144e8">

我怀疑是xcode编译的时候会产生问题，下面是报错内容，
NSBundle file:///System/Library/PrivateFrameworks/MetalTools.framework/ principal class is nil because all fallbacks have failed
Can't find or decode reasons
Failed to get or decode unavailable reasons
-[AFPreferences _languageCodeWithFallback:] No language code saved, but Assistant is enabled - returning: en-US
-[AFPreferences _languageCodeWithFallback:] No language code saved, but Assistant is enabled - returning: en-US
Unable to create bundle at URL ((null)): normalized URL null
Unable to create bundle at URL ((null)): normalized URL null
Unable to create bundle at URL ((null)): normalized URL null
WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.

**Comment by hakadao** [comment]
> Safari中的个人界面显示不出来，点进去就是登陆了，但相关的收藏和浏览器记录并不存在，我尝试了最新的几个版本都是一样的问题
> 
> <img width="150" alt="image" src="https://github.com/user-attachments/assets/35949fa0-a68d-41cf-96b1-2969d90de447">
> 
> <img width="553" alt="image" src="https://github.com/user-attachments/assets/32dc4a55-8d75-401f-80ee-5ff7af7039b3">
> 
> <img width="1283" alt="image" src="https://github.com/user-attachments/assets/6511a3c9-2b18-4559-aad4-2ec1143144e8">
> 
> 
> 
> 我怀疑是xcode编译的时候会产生问题，下面是报错内容，
> 
> NSBundle file:///System/Library/PrivateFrameworks/MetalTools.framework/ principal class is nil because all fallbacks have failed
> 
> Can't find or decode reasons
> 
> Failed to get or decode unavailable reasons
> 
> -[AFPreferences _languageCodeWithFallback:] No language code saved, but Assistant is enabled - returning: en-US
> 
> -[AFPreferences _languageCodeWithFallback:] No language code saved, but Assistant is enabled - returning: en-US
> 
> Unable to create bundle at URL ((null)): normalized URL null
> 
> Unable to create bundle at URL ((null)): normalized URL null
> 
> Unable to create bundle at URL ((null)): normalized URL null
> 
> WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
> 
> 

Safari不想支援，請自行解決問題，另外不要在無關問題下提出

**Comment by hakadao** [comment]
![image](https://github.com/user-attachments/assets/c33f73b4-ef0b-4990-a536-890f79fa1910)
